web-app/RSVP/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    # url('event/', include('event.urls')),
    url(r'^', include('event.urls')),
]

web-app/event/urls.py
from django.conf.urls import url
from . import views

app_name = 'event'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^track_id/$', views.track_id, name='track_id'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<order_id>[0-9]+)/$', views.change_destination, name='change_destination'),
    # url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
]

web-app/event/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

from django.db import models

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    o_status = models.CharField(max_length=100, blank=True, null=True)
    user_name = models.CharField(max_length=100, blank=True, null=True)
    truck = models.ForeignKey('Truck', models.DO_NOTHING, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    whid = models.IntegerField(blank=True, null=True)
    wh_x = models.IntegerField(blank=True, null=True)
    wh_y = models.IntegerField(blank=True, null=True)
    des_x = models.IntegerField(blank=True, null=True)
    des_y = models.IntegerField(blank=True, null=True)
    priority = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'orders'

class Item(models.Model):
    iid = models.AutoField(primary_key=True)
    item_id = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    count = models.IntegerField(blank=True, null=True)
    order = models.ForeignKey('Orders', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'item'

class Truck(models.Model):
    truck_id = models.IntegerField(primary_key=True)
    t_status = models.CharField(max_length=100, blank=True, null=True)
    x = models.IntegerField(blank=True, null=True)
    y = models.IntegerField(blank=True, null=True)
    towhid = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'truck'


class Warehouse(models.Model):
    whid = models.IntegerField(primary_key=True)
    x = models.IntegerField(blank=True, null=True)
    y = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'warehouse'

web-app/event/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Orders

# from .models import Event


# class EventForm(forms.ModelForm):
#
#     class Meta:
#         model = Event
#         fields = ['event_name', 'event_time', 'event_owner', 'location']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class DestinationForm(forms.ModelForm):
    des_x = forms.IntegerField
    des_y = forms.IntegerField

    class Meta:
        model = Orders
        fields = ['des_x', 'des_y']

web-app/event/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.urls import reverse
from .forms import UserForm, DestinationForm
from .models import Orders, Item



def index(request):
    if not request.user.is_authenticated:
        return render(request, 'event/login.html')
    else:
        orders = Orders.objects.filter(user_name = request.user.username)
        # return render(request, 'event/index.html', {'events': events})
        return render(request, 'event/index.html', {'orders': orders})

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'event/login.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                orders = Orders.objects.filter(user_name = request.user.username)
                return render(request, 'event/index.html', {'orders': orders})
            else:
                return render(request, 'event/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'event/login.html', {'error_message': 'Invalid login'})
    return render(request, 'event/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                orders = Orders.objects.filter(user_name=request.user.username)
                return render(request, 'event/index.html', {'orders': orders})
    context = {
        "form": form,
    }
    return render(request, 'event/register.html', context)

def track_id(request):
    q = request.POST['trackingnumber']
    error_msg = ''
    orders = Orders.objects.filter(order_id = q)
    return render(request, 'event/order.html', {'orders': orders})

def detail(request, order_id):
    if not request.user.is_authenticated:
        return redirect(reverse('event:index'))
    else:
        user = request.user
        items = Item.objects.filter(order_id=order_id)
        print(items)
        return render(request, 'event/detail.html', {'items': items, 'user': user, 'order_id': order_id})

def change_destination(request, order_id):
    if not request.user.is_authenticated:
        return redirect(reverse('event:index'))
    else:
        form = DestinationForm(request.POST or None, request.FILES or None)
        order = get_object_or_404(Orders, order_id = order_id)
        user_name = order.user_name
        orders = Orders.objects.filter(user_name=request.user.username)
        if form.is_valid():
            if order.o_status == "out for delivery":
                return render(request, 'event/index.html', {'error_message': 'This order is out for delivery, cannot change destination!', 'orders': orders})
            des = form.save(commit=False)
            order.des_x = des.des_x
            order.des_y = des.des_y
            order.save()
            return render(request, 'event/index.html', {'orders': orders})
        context = {
            "form": form,
        }
        return render(request, 'event/change_destination.html', context)

web-app/event/templates/event/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Eventing{% endblock %}</title>{# this is the title for the website tag #}
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!--bootstrap should be import first then css-->
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}"/>
    {# add static to specify the path, then the music directory and style.css file #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'event:index' %}">UPS</a>
        </div>

        <!--Items-->
        <div class="colla[se navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block events_active %}{% endblock %}">
                    <a href="{% url 'event:index' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Orders
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'event:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>


        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

web-app/event/templates/event/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}UPS{% endblock %}</title>
    {% load staticfiles %}
{#    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{#整个的模板框架#}
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
{#字体#}
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}"/>
{#引用css，背景，navbar，字体#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>#}
{#不知道有什么用#}
{#    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>#}
{#不知道有什么用#}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
{#            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
            <a class="navbar-brand" href="{% url 'event:index' %}">UPS</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'event:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'event:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

web-app/event/templates/event/change_destination.html
{% extends 'event/base.html' %}
{% block title %}Change Destination{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="panel panel-defult">
        <div class="panel-body">
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'event/form_template.html' %}
                <div class="col-sm-offset-2 col-sm-10">
                    <small style="color:orangered">Set the destination.</small>
                </div>
                <br>
                <br>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Save Destination</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

web-app/event/templates/event/detail.html
{% extends 'event/base.html' %}
{% block title %}{{ event }}{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>{{ user.username }}'s items in order {{ order_id }}</h3>
                    </div>
                </div>
            </div>

            <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Items</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        {% for item in items %}
                            <div class="col-sm-5 col-lg-4">
                                <div class="thumbnail">
                                    <div class="caption">
                                        <h4>Count: {{ item.count }}</h4>
                                        <h4>Description: {{ item.description }}</h4>
                                    </div>
                                </div>
                            </div>
                            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                        {% endfor %}
                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

web-app/event/templates/event/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

web-app/event/templates/event/index.html
{% extends 'event/base.html' %}
{% block events_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Orders</h3>
            </div>
            {% if error_message %}
                <p>&nbsp;&nbsp;&nbsp;<strong style="color: red">{{ error_message }}</strong></p>
            {% endif %}
            {% if orders %}
                {% for order in orders %}
                    <div class="col-sm-5 col-lg-4">
                        <div class="thumbnail">
                            <div class="caption">
                                <h4>Status: {{ order.o_status }}</h4>
                                <h4>Order ID: {{ order.order_id }}</h4>
                                <h4>Issued Time: {{ order.time }}</h4>
                                <a href="{% url 'event:detail' order.order_id %}" class="btn btn-primary btn-sm" role="button">View Items</a>
                                <a href="{% url 'event:change_destination' order.order_id %}"
                                   class="btn btn-primary btn-sm" role="button">Change Destination</a>
                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            {% else %}
                <div class="caption">
                    <h4>You currently don't have orders.</h4>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

web-app/event/templates/event/login.html
{% extends 'event/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
{#        md-白框的宽度 #}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Track Your Package</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'event:track_id'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-3" for="id_username">
                                Tracking Number:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="trackingnumber" type="number" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-10">
                                <button type="submit" class="btn btn-success">Track</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'event:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'event:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

web-app/event/templates/event/order.html
{% extends 'event/base.html' %}
{% block events_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        {% if orders %}
            {% for order in orders %}
                <div class="col-sm-5 col-lg-3">
                    <div class="thumbnail">
                        <div class="caption">
                            <h4>Status: {{ order.o_status }}</h4>
                            <h4>Order ID: {{ order.order_id }}</h4>
                            <h4>Issued Time: {{ order.time }}</h4>
                            <h4>Whid: {{ order.whid }}</h4>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-5 col-md-offset-0">
                <div class="thumbnail">
                    <div class="caption">
                        <h3 style="color: red">Invalid tracking number!</h3>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
        <a class="btn btn-success" href="{% url 'event:index' %}">Go Back</a>
    </div>
</div>
{% endblock %}

web-app/event/templates/event/register.html
{% extends 'event/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'event/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'event:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}